// Auto-generated by Supabase after T03.
// Regenerate with: npx supabase gen types typescript --local > src/types/database.ts
// This is a placeholder — replace after running pimsua_setup.sql.

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
